# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d36ea4fc9f20081f4979f2a1fff742ecff5184086a8aa524b7254b633632a2262fe818f92a578e0fcfc165439dddcb7f41f7087a81a36e981386853930b4d19e
  application_id: 'api-sample'
  application_secret: 'super secret key'

test:
  secret_key_base: 92d7efc5cc40782d5609452ae72669ea7b7fe5435520a0f1d811268f9486aa00c546186764d4b80fe94335c411415b87eab477bac19a87d16ea50abfb4fc0335
  application_id: 'api-sample'
  application_secret: 'super secret key'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  application_id: 'api-sample'
  application_secret: 'super secret key'
